import {
    Calendar,
    Search,
    Clipboard,
    RefreshCw,
    FileText,
    Upload,
    Send,
    Settings2,
    Eye,
    Edit,
    Trash2,
    Copy,
    CheckCircle,
    XCircle,
    ChevronDown,
    ChevronUp,
    ChevronsUpDown,
    EyeOff,
    ChevronLeft,
    ChevronRight,
    ChevronsLeft,
    ChevronsRight,
    MoreHorizontal,
    Plus,
    X,
    Check,
    PlusCircle,
    type LucideIcon,
} from 'lucide-react'

export type Icon = LucideIcon

export const Icons = {
    calendar: Calendar,
    search: Search,
    clipboard: Clipboard,
    refresh: RefreshCw,
    fileText: FileText,
    upload: Upload,
    send: Send,
    settings: Settings2,
    eye: Eye,
    edit: Edit,
    trash: Trash2,
    copy: Copy,
    check: CheckCircle,
    close: XCircle,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    chevronsUpDown: ChevronsUpDown,
    eyeOff: EyeOff,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronsLeft: ChevronsLeft,
    chevronsRight: ChevronsRight,
    moreHorizontal: MoreHorizontal,
    plus: Plus,
    x: X,
    checkIcon: Check,
    plusCircle: PlusCircle,
}

